### ISSUE TITLE
Is patchelf-0.16 compatible with NixOS patchelf-0.8 ?

### ISSUE THREAD

**Issue by liubenyuan** [darealshinji/patchelfmod#3]
Hi, thanks for this package.

Is patchelf-0.16 compatible with NixOS patchelf-0.8 ? so that I can replace the patchelf package in archlinux with this one.

**Comment by darealshinji** [comment]
You mean patchelfmod, right? The command line arguments might be a bit different in some cases, but you can replace it with the latest development version from the NixOS git master branch. I stopped developing on the modded version after all the recent upstream changes.
Just make sure to not use the NixOS release version 0.8 which is outdated.
Eelco anounced that he will soon publish a new release: https://github.com/NixOS/patchelf/issues/31#issuecomment-187254266

**Comment by liubenyuan** [comment]
Thanks !
